[build]
  publish = "public"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    fontSrc = "'self'"
    styleSrc = "https://cdnjs.cloudflare.com/ 'unsafe-hashes'"
    scriptSrc = "'self' https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com https://cdnjs.cloudflare.com/ https://d33wubrfki0l68.cloudfront.net/"
    frameSrc = "'self' https://youtube.com https://www.youtube.com https://www.youtube-nocookie.com"
    frameAncestors = "'none'"
    connectSrc = "'self' https://*.analytics.google.com/ https://*.google-analytics.com"
    imgSrc = "'self' https://*.analytics.google.com/ https://*.google-analytics.com"
    workerSrc = "'self'"
    manifestSrc = "'self'"