[build]
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    styleSrc = "'unsafe-hashes'"
    scriptSrc = "'self' https://region1.analytics.google.com/ https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com https://cdnjs.cloudflare.com/"
    frameSrc = "'self' https://youtube.com https://www.youtube.com https://www.youtube-nocookie.com"
    frameAncestors = "'none'"